---
- name: Install and configure MicroK8s cluster
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install MicroK8s
      snap:
        name: microk8s
        state: present
        classic: yes

    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Enable MicroK8s addons
      command: microk8s enable dns storage
      register: microk8s_enable_addons
      changed_when: "'Nothing to do' not in microk8s_enable_addons.stdout"

    - name: Enable HA MicroK8s services
      command: microk8s enable ha-cluster

    - name: Wait for the MicroK8s API server to be ready
      command: microk8s status --wait-ready

    - name: Get the join command from microk8s-vm-1
      shell: "microk8s add-node | grep 'microk8s join' | head -n 1"
      register: join_command
      when: inventory_hostname == 'microk8s-vm-1'

    - name: Register the join command for other nodes
      set_fact:
        join_command: "{{ hostvars['microk8s-vm-1'].join_command.stdout }}"
      when: inventory_hostname != 'microk8s-vm-1'

    - name: Join the cluster (with retries)
      shell: "{{ join_command }}"
      register: join_output
      retries: 5
      delay: 10
      until: join_output.rc == 0
      when: inventory_hostname != 'microk8s-vm-1'

    - name: Display join result
      debug:
        msg: "{{ join_command }}"
      when: inventory_hostname != 'microk8s-vm-1'
