---
- name: Update web servers
  hosts: microk8s-learn-platform
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: true
