---
- name: Create monitoring namespace if it doesn't exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "monitoring"
    state: present

- name: Add Prometheus community Helm repo
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install kube-prometheus-stack Helm chart
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "68.2.1"
    release_namespace: "monitoring"
    create_namespace: false
    values:
      prometheus:
        service:
          type: NodePort
      grafana:
        enabled: false
    wait: true
