---
- name: Generate kubeconfig from microk8s
  command: microk8s config
  register: kubeconfig_output
  
- name: Copy kubeconfig to local machine if not present
  become: false
  local_action:
    module: copy
    args:
      content: "{{ kubeconfig_output.stdout }}"
      dest: "{{ kubeconfig }}"